routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('login', '\App\Http\Controllers\Auth\LoginController@authenticate');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'role', 'middleware' => ['auth','permission'], 'as' => 'role.'], function () {
    Route::get('/', [App\Http\Controllers\RoleController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\RoleController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\RoleController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\RoleController::class, 'edit'])->name('edit');
    Route::post('/update/{id}', [App\Http\Controllers\RoleController::class, 'update'])->name('update');
    // Route::delete('/delete/{id}', [App\Http\Controllers\RoleController::class, 'delete'])->name('delete');
    Route::get('/status', [App\Http\Controllers\RoleController::class, 'status'])->name('status');
});

Route::group(['prefix' => 'employee', 'middleware' => ['auth','permission'], 'as' => 'employee.'], function () {
    Route::get('/', [App\Http\Controllers\EmployeeController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\EmployeeController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\EmployeeController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\EmployeeController::class, 'edit'])->name('edit');
    Route::get('/detail/{id}', [App\Http\Controllers\EmployeeController::class, 'detail'])->name('detail');
    Route::post('/update/{id}', [App\Http\Controllers\EmployeeController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [App\Http\Controllers\EmployeeController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'candidate', 'middleware' => ['auth','permission'], 'as' => 'candidate.'], function () {
    Route::get('/', [App\Http\Controllers\CandidateController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\CandidateController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\CandidateController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\CandidateController::class, 'edit'])->name('edit');
    Route::get('/detail/{id}', [App\Http\Controllers\CandidateController::class, 'detail'])->name('detail');
    Route::post('/update/{id}', [App\Http\Controllers\CandidateController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [App\Http\Controllers\CandidateController::class, 'delete'])->name('delete');
});
Route::get('/download/{id}', [App\Http\Controllers\CandidateController::class, 'download'])->name('candidate.download')->middleware('auth');

app/Models/Candidate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Candidate extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'phone_number',
        'last_education',
        'education',
        'birthdate',
        'experience',
        'last_position',
        'position_notes',
        'applied_position',
        'top_skill',
        'resume',
        'address',
        'gender',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class,'applied_position','id');
    }

    public function lastEducation()
    {
        return $this->belongsTo(LastEducation::class,'last_education','id');
    }

    public function lastPosition()
    {
        return $this->belongsTo(LastPosition::class,'last_position','id');
    }
}

app/Http/Controllers/API/v1/CandidateController.php
<?php

namespace App\Http\Controllers\API\v1;

use App\Http\Controllers\Controller;
use App\Models\Candidate;
use Spatie\Permission\Models\Role;
use App\Models\LastEducation;
use App\Models\LastPosition;
use App\Models\Skill;
use Carbon\Carbon;
use Exception;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Http\Requests\CandidateRequest;
use Yajra\DataTables\Facades\DataTables;

class CandidateController extends Controller
{
    private $candidate;
    public function __construct(Candidate $candidate)
    {
        $this->candidate = $candidate;
    }
    /**
     * @OA\Get(
     ** path="/candidate",
     *   tags={"Candidate"},
     *   summary="get-candidate",
     *   operationId="GetCandidate",
     * security={ {"api_key_security": {} }},
     * 
     *    @OA\Parameter(
     *      name="page",
     *      in="query",
     *      required=false,
     *      @OA\Schema(
     *           type="number"
     *      )
     *   ),
     *
     *   @OA\Response(
     *      response=200,
     *       description="Success",
     *      @OA\MediaType(
     *           mediaType="application/json",
     *      )
     *   ),
     *   @OA\Response(
     *      response=401,
     *       description="Unauthenticated"
     *   ),
     *   @OA\Response(
     *      response=400,
     *      description="Bad Request"
     *   ),
     *   @OA\Response(
     *      response=404,
     *      description="not found"
     *   ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     *)
     **/
    public function fetchAll(Request $request)
    {
        try {
            $data = $this->candidate->with('role','lastEducation','lastPosition')->paginate(10, ['*'], 'page', ($request->page ?? 1));

            $header = [
                'code' => 200,
                'error' => false,
                'message' => null
            ];

            return response()->json(['meta' => $header, 'data' => $data]);
        } catch (\Throwable $th) {
            $header = [
                'code' => $th->getCode(),
                'error' => true,
                'message' => $th->getMessage()
            ];

            return response()->json(['meta' => $header, 'data' => null]);
        }
    }
    /**
     * @OA\Post(
     ** path="/candidate/store",
     *   tags={"Candidate"},
     *   summary="save-candidate",
     *   operationId="saveCandidate",
     * security={ {"api_key_security": {} }},
 *
 *     @OA\RequestBody(
     *     required=true,
     *     @OA\MediaType(
     *       mediaType="multipart/form-data",
     *       @OA\Schema(
     *         required={"name", "email","phone_number","address","gender","last_education","birthdate","education","experience","last_position","applied_position","skill","resume"},
     *         @OA\Property(property="name", type="string", example="john"),
     *         @OA\Property(property="email", type="string", example="test@test.com"),
     *         @OA\Property(property="phone_number", type="string", example="08221123123"),
     *         @OA\Property(property="address", type="string",example="Bandung"),
     *         @OA\Property(property="gender", enum={"male","female"}, example="male"),
     *         @OA\Property(property="last_education", enum={"Tidak/Belum Sekolah","Tidak Tamat SD/Sederajat","Tamat SD/Sederajat","SLTP/Sederajat","SLTA/Sederajat","Diploma I/II","Akademi/Diploma III/Sarjana Muda","Diploma IV/Strata I","Strata II","Strata III"}, example="Tidak/Belum Sekolah"),
     *         @OA\Property(property="education", type="string", example="Univ. XYZ"),
     *         @OA\Property(property="birthdate", type="string", example="1997-09-22"),
     *         @OA\Property(property="experience", type="string", example="5 Tahun"),
     *         @OA\Property(property="last_position", type="string", example="Back End Developer"),
     *         @OA\Property(property="applied_position", enum={"Senior HRD","HRD","Senior PHP Developer"}, example="Senior PHP Developer"),
     *         @OA\Property(property="skill", type="string", example="php, mysql"),
     *         @OA\Property(property="resume", type="string", format="binary"),
     *       )
     *     )
 *       
 *      ),
     *    @OA\Response(
     *      response=200,
     *       description="Success",
     *   ),
     *   @OA\Response(
     *      response=401,
     *       description="Unauthenticated"
     *   ),
     *   @OA\Response(
     *      response=400,
     *      description="Bad Request"
     *   ),
     *   @OA\Response(
     *      response=404,
     *      description="not found"
     *   ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     * )
     */
    public function store(CandidateRequest $request)
    {
        $message = null;
        try {
            DB::beginTransaction();

            if ($request->has('resume')) {
                $file = $request->resume;
                $valid_ext = ['pdf'];
                $valid_mime = ['pdf','application/pdf'];

                if (in_array($file->getClientOriginalExtension(), $valid_ext)) {
                    if (in_array($file->getMimeType(), $valid_mime)) {
                        $filename = \Str::random(15) . '_' . sanitizeString($file->getClientOriginalName());
                        $filepath = 'candidate/' . Carbon::now()->timestamp . '/' . \Str::uuid();

                        $path = Storage::disk('local')->putFileAs($filepath, $file, $filename, 'public');

                    } else {
                        throw new Exception("Tipe file tidak sesuai", 500);
                    }
                } else {
                    throw new Exception("Tipe file tidak sesuai", 500);
                }

            }
            
            $slug_education = strtolower(preg_replace('~[^\pL\d]+~u', '-', $request->last_education));
            $lastEducation = LastEducation::where('slug', $slug_education)->first();
            if(!$lastEducation){
                $lastEducation = LastPosition::create([
                    'name' => $request->last_education,
                    'slug' => $slug_education,
                    'description' => null,
                    'status' => true,
                ]);
            }

            $slug_position = strtolower(preg_replace('~[^\pL\d]+~u', '-', $request->last_position));
            $lastPosition = LastPosition::where('slug', $slug_position)->first();
            if(!$lastPosition){
                $lastPosition = LastPosition::create([
                    'name' => $request->last_position,
                    'slug' => $slug_position,
                    'description' => null,
                    'status' => true,
                ]);
            }

            $slug_applied = strtolower(preg_replace('~[^\pL\d]+~u', '-', $request->applied_position));
            $appliedPosition = Role::where('slug', $slug_applied)->first();
            if(!$appliedPosition){
                $appliedPosition = Role::create([
                    'name' => $request->applied_position,
                    'slug' => $slug_position,
                    'description' => null,
                    'status' => true,
                ]);
            }

            $skill = explode(",", $request->skill);

                
            $data = [
                'name' => $request->name,
                'email' => $request->email,
                'phone_number' => $request->phone_number,
                'last_education' => $lastPosition->id ?? 5,
                'education' => $request->education,
                'birthdate' => Carbon::parse($request->birthdate),
                'experience' => $request->experience,
                'last_position' => $lastPosition->id ?? 81,
                'position_notes' => $request->position_notes ?? null,
                'applied_position' => $appliedPosition->id ?? 4,
                'top_skill' => json_encode($skill) ?? null,
                'resume' => $path ?? '-',
                'gender' => $request->gender,
                'address' => $request->address,
            ];

            $candidate = $this->candidate->create($data);
            
            if(!$candidate){
                $message = 'Gagal menambahkan kandidat !';
                DB::rollback();
            }
            DB::commit();
            
            $header = [
                'code' => 200,
                'error' => false,
                'message' => null
            ];

            return response()->json(['meta' => $header, 'data' => $data]);

        } catch (\Throwable $th) {
            $header = [
                'code' => $th->getCode(),
                'error' => true,
                'message' => $th->getMessage()
            ];

            return response()->json(['meta' => $header, 'data' => null]);
        }
    }
    /**
     * @OA\Post(
     ** path="/candidate/update/{id}",
     *   tags={"Candidate"},
     *   summary="update-candidate",
     *   operationId="updateCandidate",
     * security={ {"api_key_security": {} }},
     * 
     *    @OA\Parameter(
     *      name="id",
     *      in="path",
     *      required=true,
     *      @OA\Schema(
     *           type="number"
     *      )
     *   ),
 *
 *     @OA\RequestBody(
     *     required=true,
     *     @OA\MediaType(
     *       mediaType="multipart/form-data",
     *       @OA\Schema(
     *         @OA\Property(property="name", type="string"),
     *         @OA\Property(property="email", type="string"),
     *         @OA\Property(property="phone_number", type="string"),
     *         @OA\Property(property="address", type="string"),
     *         @OA\Property(property="gender", enum={"male","female"}),

resources/views/admin/candidate/detail.blade.php
@extends("layout.template")

@push('custom-css')
<link rel="stylesheet" type="text/css" href="{{ asset('template/') }}/plugins/datepicker/bootstrap-datepicker.min.css" />
<style>
    .swal-modal{
        width: 375px !important;
    }
    .swal-footer{
        text-align: center !important;
    }
    .img-preview{
      width: 5rem;
    }
    .address {
      resize: none;
    }
</style>
@endpush

@section('content')

@if (old())
  {{-- expr --}}
  {{-- @dd(old()) --}}
@endif
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>Detail Kandidat</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                              <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->name ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="email" class="col-sm-2 col-form-label">Alamat Email</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->email ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->address ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="birthdate" class="col-sm-2 col-form-label">Tanggal Lahir</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->birthdate ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="gender" class="col-sm-2 col-form-label">Jenis Kelamin</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->gender ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="phone_number" class="col-sm-2 col-form-label">No Telepon</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->phone_number ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="last_education" class="col-sm-2 col-form-label">Tingkat Pendidikan Terakhir</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->lastEducation->name ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="education" class="col-sm-2 col-form-label">Pendidikan Terakhir</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->education ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="last_position" class="col-sm-2 col-form-label">Posisi Terakhir</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->lastPosition->name ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="experience" class="col-sm-2 col-form-label">Pengalaman (Dalam Tahun)</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->experience ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="applied_position" class="col-sm-2 col-form-label">Applied Positions</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->role->name ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="skill" class="col-sm-2 col-form-label">Skill</label>
                                <div class="col-sm-10">
                                  <p>{{ @$data->top_skill ?? '-' }}</p>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="resume" class="col-sm-2 col-form-label">Resume</label>
                                <div class="col-sm-10">
                                  <a href="'{{route('candidate.download', encrypt($data->id))}} '" class="btn btn-success btn-xs"><i class="fa fa-download"></i>&nbsp; Download Resume</a>&nbsp;
                                </div>
                              </div>
                            </div>

                            <div class="card-footer">
                              <a href="{{ route('candidate.index') }}" id="batal" class="btn btn-default">Batal</a>
                            </div>
                            <!-- /.card-body -->
                          </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')

<script>
  $(document).ready(function(){
    $("#phone_number").on("keypress keyup blur",function (event) {    
        $(this).val($(this).val().replace(/[^\d].+/, ""));
        if (event.which > 31 && (event.which < 48 || event.which > 57)) {
            event.preventDefault();
        }
    });
  });

</script>

@include("admin.candidate.script")
@endpush

resources/views/admin/candidate/index.blade.php
@extends("layout.template")

@push('custom-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <style>
        div.dataTables_wrapper div.dataTables_filter input {
            padding-right: 1%
        }
    </style>
@endpush

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>Data Kandidat</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                            <div class="card-header">
                                @can('candidate.create')
                                    <div class="row">
                                        <a href="{{ route('candidate.create') }}" class="btn btn-success" id="btn-upload">
                                            <i class="fa fa-plus"></i> Tambah Kandidat
                                        </a>
                                    </div>
                                @endcan
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="candidates-table" class="table table-bordered table-striped" style="width: 100%">
                                <thead>
                                    <th>No</th>
                                    <th>Applied Position</th>
                                    <th>Last Position</th>
                                    <th>Last Education</th>
                                    <th>Top Skill</th>
                                    <th>Name</th>
                                    <th>Resume</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </thead>
                                <tbody>
                                </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')
@include("admin.candidate.script")
@endpush

resources/views/admin/candidate/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('template/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="{{ asset('js') }}/moment.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datepicker/bootstrap-datepicker.min.js"></script>

<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();

  $('#candidates-table').DataTable({
    processing: true,
    "language": { "emptyTable": "Tidak ada data",
                },
    serverSide: true,
    ajax: '{{ route("datatable.candidate") }}',
    columns: [
      {data: 'DT_RowIndex', name: 'no', orderable: false, searchable: false},
      {data: 'applied_position', name: 'applied_position'},
      {data: 'last_position', name: 'last_position'},
      {data: 'last_education', name: 'last_education'},
      {data: 'top_skill', name: 'top_skill'},
      {data: 'name', name: 'name'},
      {data: 'resume', name: 'resume'},
      {data: 'created_at', name: 'created_at', orderable: false, searchable: false},
      {data: 'action', name: 'action', orderable: false, searchable: false}
    ],
    initComplete: function(){
        var api = this.api();
        $('#candidates-table_filter input')
            .off('.DT')
            .on('keyup.DT', function (e) {
                if (e.keyCode == 13) {
                    api.search(this.value).draw();
                }
            });
      },
  });

  var date = new Date();
  date.setFullYear(date.getFullYear() - 17);

  $('#birthdate').datepicker('option', 'maxDate', date);
  $('#birthdate').datepicker("setDate", date);
  $("#last_education").select2();
  $("#last_position").select2();
  $("#applied_positions").select2();
  $("#skill").select2();
});
</script>