routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('login', '\App\Http\Controllers\Auth\LoginController@authenticate');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'role', 'middleware' => ['auth','permission'], 'as' => 'role.'], function () {
    Route::get('/', [App\Http\Controllers\RoleController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\RoleController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\RoleController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\RoleController::class, 'edit'])->name('edit');
    Route::post('/update/{id}', [App\Http\Controllers\RoleController::class, 'update'])->name('update');
    // Route::delete('/delete/{id}', [App\Http\Controllers\RoleController::class, 'delete'])->name('delete');
    Route::get('/status', [App\Http\Controllers\RoleController::class, 'status'])->name('status');
});

Route::group(['prefix' => 'employee', 'middleware' => ['auth','permission'], 'as' => 'employee.'], function () {
    Route::get('/', [App\Http\Controllers\EmployeeController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\EmployeeController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\EmployeeController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\EmployeeController::class, 'edit'])->name('edit');
    Route::get('/detail/{id}', [App\Http\Controllers\EmployeeController::class, 'detail'])->name('detail');
    Route::post('/update/{id}', [App\Http\Controllers\EmployeeController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [App\Http\Controllers\EmployeeController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'candidate', 'middleware' => ['auth','permission'], 'as' => 'candidate.'], function () {
    Route::get('/', [App\Http\Controllers\CandidateController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\CandidateController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\CandidateController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\CandidateController::class, 'edit'])->name('edit');
    Route::get('/detail/{id}', [App\Http\Controllers\CandidateController::class, 'detail'])->name('detail');
    Route::post('/update/{id}', [App\Http\Controllers\CandidateController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [App\Http\Controllers\CandidateController::class, 'delete'])->name('delete');
});
Route::get('/download/{id}', [App\Http\Controllers\CandidateController::class, 'download'])->name('candidate.download')->middleware('auth');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'address',
        'phone_number',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'id', 'employee_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Models\Employee;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use Auth;
use Carbon\Carbon;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Hash;

class EmployeeController extends Controller
{
    private $employee;
    public function __construct(Employee $employee)
    {
        $this->employee = $employee;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.employee.index');
    }

    public function datatable(Request $request)
    {
        $data = $this->employee->all();

        return DataTables::of($data)
            ->addIndexColumn()
            ->addColumn('role', function ($data) {
                return $data->user->role ? $data->user->role->name : '-';
            })
            ->addColumn('email', function ($data) {
                return $data->user ? $data->user->email : '-';
            })
            ->editColumn('created_at', function ($data){
                return Carbon::parse($data->created_at)->timezone('Asia/Jakarta')->format('d-M-Y');
            })
            ->addColumn('action', function ($data) {
                $action = '';
                $action .= user()->can('employee.edit') ? '<a href="' . route('employee.edit', encrypt($data->id)) . '" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="' . __('Edit Karyawan') . '"><i class="fa fa-edit"></i></a>&nbsp;' : '';
                
                $action .= user()->can('employee.delete') ? '<form method="post" action="' . route('employee.delete', encrypt($data->id)) . '" style="display: inline">
                    <input type="hidden" name="_token" value="' . csrf_token() . '"><input type="hidden" name="_method" value="delete">
                    <button class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Hapus data ini?" onclick="return confirm(\'' . __('Hapus Data ini?') . '\')"><i class="fa fa-trash"></i></button>&nbsp;
                    </form>' : '';

                return '<div class="d-flex">' . $action . '</div>';
            })
            ->rawColumns(['status','action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['roles'] = Role::all();
        return view('admin.employee.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $redirect = back()->withInput();
        try {
            DB::beginTransaction();
             $data = [
                'name' => $request->name,
                'gender' => $request->gender,
                'address' => $request->address,
                'phone_number' => $request->phone_number,
            ];

            $employee = $this->employee->create($data);
            
            if(!$employee){
                toastr()->error('Gagal menambahkan karyawan !');
                DB::rollback();
            }
            
            $data_user = [
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'role_id' => $request->role_id,
                'employee_id' => $employee->id
            ];

            $user = User::create($data_user);
            
            if(!$user){
                toastr()->error('Gagal menambahkan karyawan !');
                DB::rollback();
            }

            $redirect = redirect()->route('employee.index');
            toastr()->success('Karyawan baru telah berhasil ditambahkan');
            DB::commit();
        } catch (\Exception $e) {
            Log::info('Data karyawan baru gagal dibuat detail: ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            toastr()->error('Gagal menambahkan karyawan !');
            DB::rollback();
        }
        return $redirect;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function detail(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['data'] = $this->employee->find(decrypt($id));
        $data['roles'] = Role::all();

        return view('admin.employee.create', $data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, $id)
    {
        try {
            DB::beginTransaction();
            $redirect = back()->withInput();
            $id = decrypt($id);

            $employee = $this->employee->find($id);

            if($employee){

                $data = [
                    'name' => $request->name,
                    'gender' => $request->gender,
                    'address' => $request->address,
                    'phone_number' => $request->phone_number,
                ];

                $save = $employee->update($data);

                if(!$save){
                    toastr()->error('Gagal mengubah data karyawan !');
                    DB::rollback();
                }
                
                $user = User::where('employee_id', $id)->first();

                if($user){

                    if ($request->password) {
                        $password = Hash::make($request->password);
                    } else {
                        $password = $user->password;
                    }
                
                    $data_user = [
                        'email' => $request->email,
                        'customer' => $request->customer,
                        'password' => $password,
                        'role_id' => $request->role_id,
                        'employee_id' => $employee->id
                    ];
        
                    $save_user = $user->update($data_user);
                    
                    if(!$save_user){
                        toastr()->error('Gagal menambahkan karyawan !');
                        DB::rollback();
                    }

                }else{
                    toastr()->error('Data karyawan tidak ditemukan !');
                    DB::rollback();
                }
            }else{
                toastr()->error('Data karyawan tidak ditemukan !');
                DB::rollback();
            }

            $redirect = redirect()->route('employee.index');
            toastr()->success('Data Karyawan telah berhasil diubah');
            DB::commit();
        } catch (\Exception $e) {
            Log::info('Data karyawan baru gagal diubah detail: ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            toastr()->error('Gagal mengubah data karyawan !');
            DB::rollback();
        }
        return $redirect;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        try {
            DB::beginTransaction();

            $id = decrypt($id);

            if ($check = $this->employee->find($id)) {
                if($check->user->id == 1){
                    toastr()->error('Karyawan tidak diizinkan untuk dihapus');
                    DB::rollback();
                }else{
                    $check->delete();
                    User::where('employee_id', $id)->delete();
                    toastr()->success('Karyawan telah dihapus');
                    DB::commit();
                }
            } else {
                toastr()->error('karyawan tidak ditemukan');
                DB::rollback();
            }
        } catch (\Exception $e) {
            Log::info('Gagal menghapus data karyawan : ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            toastr()->error('Gagal menghapus karyawan !');
            DB::rollback();
        }
        return back();
    }
}

resources/views/admin/employee/create.blade.php
@extends("layout.template")

@push('custom-css')
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
<style>
    .swal-modal{
        width: 375px !important;
    }
    .swal-footer{
        text-align: center !important;
    }
    .img-preview{
      width: 5rem;
    }
    .address {
      resize: none;
    }
</style>
@endpush

@section('content')

@if (old())
  {{-- expr --}}
  {{-- @dd(old()) --}}
@endif
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>{{ (@$data) ? 'Ubah' : 'Buat' }} Karyawan</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                          <form action="{{ (@$data) ? route('employee.update', encrypt(@$data->id)) : route('employee.store') }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                            @csrf
                            <!-- /.card-header -->
                            <div class="card-body">
                              <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <input type="text" name="name" class="form-control" id="name" value="{{ (@$data->name) ?? old('name') }}" placeholder="Nama" required>
                                  {!! @$errors ? $errors->first('name', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-name"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="role_id" class="col-sm-2 col-form-label">Posisi <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <select name="role_id" class="form-control" id="role_id" required>
                                    <option value="" disabled {{ (@$data->gender) ?? 'selected' }}>Pilih Posisi</option>
                                      @foreach (@$roles as $key => $role)
                                          <option value="{{ $role->id }}" {{ ((old('role_id') == $role->id) || ((@$data->user->role_id) == $role->id)) ? 'selected' : '' }} >{{ $role->name }}</option>
                                      @endforeach
                                  </select>
                                  {!! @$errors ? $errors->first('role_id', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-role_id"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="email" class="col-sm-2 col-form-label">Alamat Email</label>
                                <div class="col-sm-10">
                                  <input type="email" name="email" class="form-control" value="{{ (@$data->user->email) ?? old('email') }}" id="email" placeholder="Alamat Email">
                                  {!! @$errors ? $errors->first('email', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-email"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="address" class="col-sm-2 col-form-label">Alamat <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <textarea name="address" class="form-control address" id="address" placeholder="Alamat" required cols="3" rows="3">{{ (@$data->address) ?? old('address') }}</textarea>
                                  {!! @$errors ? $errors->first('address', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-address"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="phone_number" class="col-sm-2 col-form-label">No Telepon <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <input type="tel" name="phone_number" class="form-control" id="phone_number"  maxlength="13" minlength="10" value="{{ (@$data->phone_number) ?? old('phone_number') }}" placeholder="No Telepon" required>
                                  {!! @$errors ? $errors->first('phone_number', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-phone_number"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="gender" class="col-sm-2 col-form-label">Jenis Kelamin <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <select name="gender" class="form-control" id="gender" required>
                                    <option value="" disabled {{ (@$data->gender) ?? 'selected' }}>Jenis Kelamin</option>
                                    <option value="male" {{ ((old('gender') == "male") || ((@$data->gender) == "male")) ? 'selected' : '' }}>Pria</option>
                                    <option value="female" {{ ((old('gender') == "female") || ((@$data->gender) == "female")) ? 'selected' : '' }}>Wanita</option>
                                  </select>
                                  {!! @$errors ? $errors->first('gender', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-gender"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="password" class="col-sm-2 col-form-label">Password {!! (@$data) ? '' : '<span class="required-field-sign"></span>' !!}</label>
                                <div class="col-sm-10">
                                      <div class="input-group">
                                          <input type="password" name="password" class="form-control border-right-0" id="password" placeholder="Password" {{ @$data ? '' : 'required' }}>
                                          <div class="input-group-append bg-white">
                                              <div class="btn border border-left-0" id="show">
                                                <span class="fas fa-eye"></span>
                                              </div>
                                              <div class="btn border border-left-0" id="hide" hidden>
                                                <span class="fas fa-eye-slash"></span>
                                              </div>
                                          </div>
                                      </div>
                                  {!! @$errors ? $errors->first('password', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-password"></strong>
                                    </span>
                                </div>
                              </div>

                              <div class="form-group row">
                                <label for="password_confirmation" class="col-sm-2 col-form-label">Konfirmasi Password {!! (@$data) ? '' : '<span class="required-field-sign"></span>' !!}</label>
                                <div class="col-sm-10">
                                    <div class="input-group">
                                        <input type="password" name="password_confirmation" class="form-control border-right-0" id="password_confirmation" placeholder="Konfirm Password"  {{ @$data ? '' : 'required' }}>
                                        <div class="input-group-append bg-white">
                                            <div class="btn border border-left-0" id="show_form">
                                              <span class="fas fa-eye"></span>
                                            </div>
                                            <div class="btn border border-left-0" id="hide_form" hidden>
                                              <span class="fas fa-eye-slash"></span>
                                            </div>
                                        </div>
                                    </div>
                                  {!! @$errors ? $errors->first('password_confirmation', '<code><small>:message</small></code>') : '' !!}
                                  <div style="margin-top: 7px;" id="CheckPasswordMatch"></div>
                                </div>
                              </div>
                            </div>

                            <div class="card-footer">
                              <a href="{{ route('employee.index') }}" id="batal" class="btn btn-default">Batal</a>
                              <button type="submit" class="btn btn-primary">{{ (@$data) ? 'Ubah' : 'Simpan' }}</button>
                            </div>
                            <!-- /.card-body -->
                          </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')

<script>
  $(document).ready(function(){
    $("#phone_number").on("keypress keyup blur",function (event) {    
        $(this).val($(this).val().replace(/[^\d].+/, ""));
        if (event.which > 31 && (event.which < 48 || event.which > 57)) {
            event.preventDefault();
        }
    });
    $('#show').on('click', function(){
        $('#show').attr('hidden','true');
        $('#hide').removeAttr('hidden');
        $('#password').attr('type','text');
    })
    $('#hide').on('click', function(){
        $('#show').removeAttr('hidden');
        $('#hide').attr('hidden','true');
        $('#password').attr('type','password');
    })
    $('#show_form').on('click', function(){
        $('#show_form').attr('hidden','true');
        $('#hide_form').removeAttr('hidden');
        $('#password_confirmation').attr('type','text');
    })
    $('#hide_form').on('click', function(){
        $('#show_form').removeAttr('hidden');
        $('#hide_form').attr('hidden','true');
        $('#password_confirmation').attr('type','password');
    })
      $("#password_confirmation").on('keyup', function() {
        var password = $("#password").val();
        var confirmPassword = $("#password_confirmation").val();
        if (password != confirmPassword)
          $("#CheckPasswordMatch").html("Password does not match !").css("color", "red");
        else
          $("#CheckPasswordMatch").html("Password match !").css("color", "green");
      });
  });

</script>

@include("admin.employee.script")
@endpush

resources/views/admin/employee/index.blade.php
@extends("layout.template")

@push('custom-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <style>
        div.dataTables_wrapper div.dataTables_filter input {
            padding-right: 1%
        }
    </style>
@endpush

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>Data Karyawan</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                            <div class="card-header">
                                @can('employee.create')
                                    <div class="row">
                                        <a href="{{ route('employee.create') }}" class="btn btn-success" id="btn-upload">
                                            <i class="fa fa-plus"></i> Tambah Karyawan
                                        </a>
                                    </div>
                                @endcan
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="employee-table" class="table table-bordered table-striped" style="width: 100%">
                                <thead>
                                    <th>No</th>
                                    <th>Posisi</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Alamat</th>
                                    <th>No Telp</th>
                                    <th>Tanggal dibuat</th>
                                    <th>Aksi</th>
                                </thead>
                                <tbody>
                                </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')
@include("admin.employee.script")
@endpush

resources/views/admin/employee/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('template/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();

  $('#employee-table').DataTable({
    processing: true,
    "language": { "emptyTable": "Tidak ada data",
                },
    serverSide: true,
    ajax: '{{ route("datatable.employee") }}',
    columns: [
      {data: 'DT_RowIndex', name: 'no', orderable: false, searchable: false},
      {data: 'role', name: 'role'},
      {data: 'name', name: 'name'},
      {data: 'email', name: 'email'},
      {data: 'address', name: 'address'},
      {data: 'phone_number', name: 'phone_number'},
      {data: 'created_at', name: 'created_at', orderable: false, searchable: false},
      {data: 'action', name: 'action', orderable: false, searchable: false}
    ],
    initComplete: function(){
        var api = this.api();
        $('#employee-table_filter input')
            .off('.DT')
            .on('keyup.DT', function (e) {
                if (e.keyCode == 13) {
                    api.search(this.value).draw();
                }
            });
      },
  });
});
</script>