routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('login', '\App\Http\Controllers\Auth\LoginController@authenticate');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'role', 'middleware' => ['auth','permission'], 'as' => 'role.'], function () {
    Route::get('/', [App\Http\Controllers\RoleController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\RoleController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\RoleController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\RoleController::class, 'edit'])->name('edit');
    Route::post('/update/{id}', [App\Http\Controllers\RoleController::class, 'update'])->name('update');
    // Route::delete('/delete/{id}', [App\Http\Controllers\RoleController::class, 'delete'])->name('delete');
    Route::get('/status', [App\Http\Controllers\RoleController::class, 'status'])->name('status');
});

Route::group(['prefix' => 'employee', 'middleware' => ['auth','permission'], 'as' => 'employee.'], function () {
    Route::get('/', [App\Http\Controllers\EmployeeController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\EmployeeController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\EmployeeController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\EmployeeController::class, 'edit'])->name('edit');
    Route::get('/detail/{id}', [App\Http\Controllers\EmployeeController::class, 'detail'])->name('detail');
    Route::post('/update/{id}', [App\Http\Controllers\EmployeeController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [App\Http\Controllers\EmployeeController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'candidate', 'middleware' => ['auth','permission'], 'as' => 'candidate.'], function () {
    Route::get('/', [App\Http\Controllers\CandidateController::class, 'index'])->name('index');
    Route::get('/create', [App\Http\Controllers\CandidateController::class, 'create'])->name('create');
    Route::post('/store', [App\Http\Controllers\CandidateController::class, 'store'])->name('store');
    Route::get('/edit/{id}', [App\Http\Controllers\CandidateController::class, 'edit'])->name('edit');
    Route::get('/detail/{id}', [App\Http\Controllers\CandidateController::class, 'detail'])->name('detail');
    Route::post('/update/{id}', [App\Http\Controllers\CandidateController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [App\Http\Controllers\CandidateController::class, 'delete'])->name('delete');
});
Route::get('/download/{id}', [App\Http\Controllers\CandidateController::class, 'download'])->name('candidate.download')->middleware('auth');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'description',
        'status',
        'deleted_at',
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Yajra\DataTables\Facades\DataTables;

class RoleController extends Controller
{
    public function index()
    {
        return view('admin.role.index');
    }

    public function datatable(Request $request)
    {
        $data = Role::all();

        return DataTables::of($data)
            ->addIndexColumn()
            ->editColumn('description', function ($data){
                return $data->description ?? '-';
            })
            ->editColumn('created_at', function ($data){
                return Carbon::parse($data->created_at)->timezone('Asia/Jakarta')->format('d-M-Y H:i');
            })
            ->editColumn('status', function ($data){
                $action = '<div class="custom-control custom-switch">
                        <input type="checkbox" class="status" name="status" '.$data->status ? "checked" : "" .' data-bootstrap-switch="" data-off-color="danger" data-on-color="success" >
                        </div>';
                return $action;
            })
            ->addColumn('action', function ($data) {
                $action = '';
                $action = '<a href="' . route('role.edit', encrypt($data->id)) . '" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="' . __('Edit Role') . '"><i class="fa fa-edit"></i></a>&nbsp;';
                
                return '<div class="d-flex">' . $action . '</div>';
                
            })
            ->rawColumns(['status','action'])
            ->make(true);
    }

    public function create()
    {
        return view('admin.role.create');
    }

    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            $slug = strtolower(preg_replace('~[^\pL\d]+~u', '-', $request->name));

            $req = [
                'name' => $request->name,
                'slug' => $slug,
                'description' => $request->description
            ];

            $save = Role::create($req);

            if(!$save){
                toastr()->error('Gagal menambahkan Role !');
            }

            DB::commit();

            toastr()->success('Berhasil menambahkan Role !');
            return redirect()->route('role.index');
        } catch (\Exception $e) {
            toastr()->error('Gagal menambahkan Role : ' . $e->getMessage());
            Log::info('ROLE-FAILED : failed add role cause : ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            DB::rollback();
        } catch (\Throwable $th) {
            toastr()->error('Telah Terjadi Kesalahan. Gagal menambahkan Role !');
            Log::info('ROLE-FAILED : failed add role cause : ' . substr($th->getMessage(), 0, 1000) . ' at ' . $th->getFile() . ' in line ' . $th->getLine());
            DB::rollback();
        }
        return redirect()->back()->withInput();
    }

    public function edit($id)
    {
        $data = Role::find(decrypt($id));
        return view('admin.role.create', ['data' => $data]);
    }

    public function update($id, Request $request)
    {
        try {
            $data = Role::find(decrypt($id));

            DB::beginTransaction();
            $slug = strtolower(preg_replace('~[^\pL\d]+~u', '-', $request->name));

            $req = [
                'name' => $request->name,
                'slug' => $slug,
                'description' => $request->description
            ];

            $save = $data->update($req);

            if(!$save){
                toastr()->error('Gagal mengubah Role !');
            }

            DB::commit();

            toastr()->success('Berhasil mengubah Role !');
            return redirect()->route('role.index');
        } catch (\Exception $e) {
            toastr()->error('Gagal mengubah Role : ' . $e->getMessage());
            Log::info('ROLE-FAILED : failed add role cause : ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            DB::rollback();
        } catch (\Throwable $th) {
            toastr()->error('Telah Terjadi Kesalahan. Gagal mengubah Role !');
            Log::info('ROLE-FAILED : failed add role cause : ' . substr($th->getMessage(), 0, 1000) . ' at ' . $th->getFile() . ' in line ' . $th->getLine());
            DB::rollback();
        }
        return redirect()->back()->withInput();
    }

    public function status(Request $request)
    {
        $data = Role::find($request->id);
        $status = $data->status ? false : true;
        $data->update(['status' => $status ]);
        return response()->json(['success' => 'true', 'code' => 200]);
    }
}

resources/views/admin/role/create.blade.php
@extends("layout.template")

@push('custom-css')
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
<style>
    .swal-modal{
        width: 375px !important;
    }
    .swal-footer{
        text-align: center !important;
    }
    .img-preview{
      width: 5rem;
    }
    .address {
      resize: none;
    }
</style>
@endpush

@section('content')

@if (old())
  {{-- expr --}}
  {{-- @dd(old()) --}}
@endif
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>{{ (@$data) ? 'Ubah' : 'Tambah' }} Posisi</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                          <form action="{{ (@$data) ? route('role.update', encrypt(@$data->id)) : route('role.store') }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                            @csrf
                            <!-- /.card-header -->
                            <div class="card-body">
                              <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <input type="text" name="name" class="form-control" id="name" value="{{ (@$data->name) ?? old('name') }}" placeholder="Nama" required>
                                  {!! @$errors ? $errors->first('name', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-name"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="description" class="col-sm-2 col-form-label">Deskripsi</label>
                                <div class="col-sm-10">
                                  <textarea name="description" class="form-control description" id="description" placeholder="Deskripsi" cols="3" rows="3">{{ (@$data->description) ?? old('description') }}</textarea>
                                  {!! @$errors ? $errors->first('description', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-description"></strong>
                                    </span>
                                </div>
                              </div>
                            </div>

                            <div class="card-footer">
                              <a href="{{ route('role.index') }}" id="batal" class="btn btn-default">Batal</a>
                              <button type="submit" class="btn btn-primary">{{ (@$data) ? 'Ubah' : 'Simpan' }}</button>
                            </div>
                            <!-- /.card-body -->
                          </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')

@include("admin.role.script")
@endpush

resources/views/admin/role/index.blade.php
@extends("layout.template")

@push('custom-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    
    <style>
        div.dataTables_wrapper div.dataTables_filter input {
            padding-right: 1%
        }
    </style>
@endpush

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>Data Posisi</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                            <div class="card-header">
                                <div class="row">
                                    <a href="{{ route('role.create') }}" class="btn btn-success" id="btn-upload">
                                        <i class="fa fa-plus"></i> Tambah Posisi
                                    </a>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="roles-table" class="table table-bordered table-striped" style="width: 100%">
                                <thead>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Slug</th>
                                    <th>Deskripsi</th>
                                    <th>Status</th>
                                    <th>Tanggal dibuat</th>
                                    <th>Aksi</th>
                                </thead>
                                <tbody>
                                </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')
@include("admin.role.script")
@endpush

resources/views/admin/role/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('template/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();

  $('#roles-table').DataTable({
    processing: true,
    "language": { "emptyTable": "Tidak ada data",
                },
    serverSide: true,
    ajax: '{{ route("datatable.role") }}',
    columns: [
      {data: 'DT_RowIndex', name: 'no', orderable: false, searchable: false},
      {data: 'name', name: 'name'},
      {data: 'slug', name: 'slug'},
      {data: 'description', name: 'description'},
      {data: 'status', name: 'status'},
      {data: 'created_at', name: 'created_at', orderable: false, searchable: false},
      {data: 'action', name: 'action', orderable: false, searchable: false}
    ]
  });


  // $(".status").change(function() {
  //   $.ajax({
  //     url: "{{ route('role.status')}}",
  //     type:'GET',
  //     data: {
  //       id : $(this).data('id'),
  //     },
  //     success: function(result){
        
  //     }
  //   });
// });
});
</script>